-Djsse.enableSNIExtension=false
Attempt to avoid problems when building in Travis for the itemis nexus
repository

[ERROR] Internal error: java.lang.RuntimeException:
org.apache.maven.MavenExecutionException: Could not setup plugin
ClassRealm: Plugin org.fornax.toolsupport:fornax-oaw-m2-plugin:3.4.0 or
one of its dependencies could not be resolved: Failed to read artifact
descriptor for org.fornax.toolsupport:fornax-oaw-m2-plugin:jar:3.4.0:
Could not transfer artifact
org.fornax.toolsupport:fornax-oaw-m2-plugin:pom:3.4.0 from/to
fornax.plugin.repository
(https://projects.itemis.de/nexus/content/groups/public/):
java.lang.RuntimeException: Could not generate DH keypair: Prime size
must be multiple of 64, and can only range from 512 to 1024 (inclusive)

http://stackoverflow.com/questions/7615645/ssl-handshake-alert-unrecognized-name-error-since-upgrade-to-java-1-7-0

Change-Id: I3ba032a57acbde587868b03fb2494c4270254ff3